# wrangler.toml for Deploy to Cloudflare button:
# https://developers.cloudflare.com/workers/platform/deploy-buttons/

name = "zurg-serverless"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
preview_urls = false  # Disable versioned preview URLs

[triggers]
crons = ["0 */1 * * *"]  # hourly cron triggers for cache refreshes

[vars]
RD_TOKEN = "OSKTA3VC4INRUDEEJ3K7VVZS452JLGYCQKEAP2DTTTKG344LDNYA"
USERNAME = "dineinhell"
PASSWORD = "YT5SKLZDENID6"
API_ACCOUNT_ID = "OSKTA3VC4INRUDEEJ3K7VVZS452JLGYCQKEAP2DTTTKG344LDNYA"  # auto-populated during deployment
REFRESH_INTERVAL_SECONDS = "15"
API_TIMEOUT_SECONDS = "30"
TORRENTS_PAGE_SIZE = "1000"
WORKER_NAME = "zurg-serverless"

[[d1_databases]]
binding = "DB"
database_name = "zurg-serverless-db"
database_id = "90d51bd8-b1cc-46e7-9df6-e479448dca39" # auto-populated during deployment
